version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
    branches:
      only:
        - main

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "27:54:5f:b8:eb:d3:18:2e:f1:85:5f:95:8a:83:2a:4c"

      - checkout

      - restore_cache:
          keys:
            - an-ui-dependencies-{{ checksum "package.json" }}
            # 如果找不到完全匹配的缓存，使用最新缓存
            - an-ui-dependencies-

      # 安装依赖
      - run:
        name: Install
        command: npm install

      # 设置缓存
      - save_cache:
          paths:
            - node_modules
          key: an-ui-dependencies-{{ checksum "package.json" }}

      # 检查 node 及 npm 版本
      - run: node --version && npm -v

      - run: npm run build-doc
